apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadastro-api-database-postgres
  labels:
    app: cadastro-api-database-postgres
spec:
  selector:
    matchLabels:
      app: cadastro-api-database-postgres
  replicas: 2
  template:
    metadata:
      labels:
        app: cadastro-api-database-postgres
    spec:
      containers:
        - name: cadastro-api-database-postgres
          image: postgres:15
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
           - name: POSTGRES_USER
             valueFrom:
               secretKeyRef:
                 name: postgres-secrets
                 key: username
           - name: POSTGRES_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: postgres-secrets
                 key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: cadastro-persistent-volume
      volumes:
        - name: cadastro-persistent-volume
          persistentVolumeClaim:
            claimName: cadastro-pvc