apiVersion: v1
kind: Service
metadata:
  name: cadastro-api-database-postgres
  labels:
    app: cadastro-api-database-postgres
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: cadastro-api-database-postgres