kind: PersistentVolume
apiVersion: v1
metadata:
  name: cadastro-pv
  labels:
    type: local
    app: cadastro-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/cadastro/data"