kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cadastro-pvc
  labels:
    app: cadastro-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi