apiVersion: v1
kind: Service
metadata:
  name: cadastro-api-app
  labels:
    app: cadastro-api-app
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 1337
  selector:
   app: cadastro-api-app