apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadastro-api-app
  labels:
    app: cadastro-api-app
spec:
  selector:
    matchLabels:
      app: cadastro-api-app
  replicas: 2
  template:
    metadata:
      labels:
        app: cadastro-api-app
    spec:
      containers:
        - name: cadastro-api-app
          image: andersonbptst/cadastro-api-app:1.0.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 1337
          env:
           - name: DATABASE_HOST
             value: "10.96.37.149"
           - name: DATABASE_USERNAME
             valueFrom:
               secretKeyRef:
                 name: postgres-secrets
                 key: username
           - name: DATABASE_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: postgres-secrets
                 key: password         